language: r
env: _R_CHECK_CRAN_INCOMING_=FALSE
sudo: required
warnings_are_errors: false

before_install:
  - sudo apt-get install -y libudunits2-dev

r:
  - release

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - covr
  - devtools

r_github_packages:
  - robsalasco/sinimr

after_success:
  - Rscript -e 'library(covr);codecov()'